# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alchemy-FileManager
version:      0.24
version_from: lib/Alchemy/FileManager.pm
installdirs:  site
requires:
    File::Copy:                    0
    File::Find::Rule:              0
    File::Path:                    0
    KrKit:                         0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
